[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "said"
version = "0.2.2"
description = "Audio-driven Speech Animation with Diffusion"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name = "inkyupark", email = "inkyupark@krafton.com" },
]
dependencies = [
    "diffusers[torch]==0.12.1",
    "einops",
    "numpy",
    "pandas",
    "pillow",
    "torch",
    "torchaudio",
    "tqdm",
    "transformers",
]

[project.optional-dependencies]
dev = [
    "accelerate",
    "black",
    "tensorboard",
]

[tool.setuptools]
packages = ["said"]

[tool.black]
include = '''
/(
    blender-addon
  | said
  | script
)/.*\.py$
'''
